name: dart_vst_host
description: Minimal VST3 host via FFI wrapping Steinberg hosting helpers
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  ffi: ^2.1.0
  meta: ^1.12.0
dev_dependencies:
  test: ^1.24.0